import os
import logging
from datetime import datetime
from typing import List, Dict

logger = logging.getLogger(__name__)


class SessionEpilogue:
    """
    会话总结与终章处理逻辑。
    负责在会话结束时固化知识，防止知识流失。
    """

    def __init__(self, storage_dir: str = ".rooster/sessions"):
        self.storage_dir = storage_dir
        os.makedirs(self.storage_dir, exist_ok=True)

    async def finalize_session(
        self, session_id: str, history: List[Dict[str, str]], memory_manager: any, llm_client: any
    ):
        """
        会话正常结束时的收尾动作。
        """
        if not history:
            return

        logger.info(f"🎬 正在执行会话终章处理: {session_id}")

        # 1. 强制蒸馏历史记录（存入 LTM）
        # 1. Force distill history into LTM
        try:
            from utils.config import settings

            await memory_manager.distill_history(
                llm_client=llm_client, model=getattr(settings, "CLOUD_MODEL", "qwen-max"), history=history
            )
            logger.info(f"✅ [{session_id}] 历史知识已成功蒸馏至 LTM。")
        except Exception as e:
            logger.error(f"❌ 蒸馏历史失败: {e}")

        # 2. 生成本地 Markdown 摘要文件（如果会话较长）
        # 2. Generate local Markdown summary file (if session is long enough)
        if len(history) > 10:
            summary_path = os.path.join(self.storage_dir, f"{session_id}_summary.md")
            try:
                with open(summary_path, "w", encoding="utf-8") as f:
                    f.write(f"# Session Summary: {session_id}\n")
                    f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                    f.write("## 核心对话脉络\n")
                    # 这里可以进一步调用 LLM 生成摘要，暂以记录最后状态为主
                    # Could call LLM for summary; for now just record final state
                    f.write(f"Total Turns: {len(history) // 2}\n")
                    f.write("\n---\n*Generated by Rooster Session Epilogue*")
                logger.info(f"✅ 已生成会话摘要文件: {summary_path}")
            except Exception as e:
                logger.error(f"❌ 生成摘要文件失败: {e}")
