import asyncio
import logging
import sys
import os
import getpass

# Disable tqdm progress bars globally (they pollute logs)
os.environ["TQDM_DISABLE"] = "1"
# Suppress noisy warnings
import warnings

warnings.filterwarnings("ignore", message=".*pkg_resources.*")
warnings.filterwarnings("ignore", message=".*UNEXPECTED.*")
from dotenv import load_dotenv

# 确保 src 目录和项目根目录在搜索路径中
# Ensure src directory and project root are in the search path
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)
project_root = os.path.dirname(current_dir)  # rooster/
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# 🚀 预先同步导入 huggingface_hub 解决多线程并发导入死锁
# Pre-import huggingface_hub synchronously to prevent multi-threaded import deadlock
try:
    pass
except Exception:
    pass

from launcher import RoosterLauncher

# 预加载环境变量
# Pre-load environment variables
load_dotenv()

# 全局日志配置
# Global logging configuration
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", stream=sys.stdout
)
logger = logging.getLogger("RoosterMain")

# 🤫 静默冗余日志，但保留 Rooster 核心日志
# Silence verbose subsystem logs, but keep Rooster core logs
logging.getLogger("lark").setLevel(logging.WARNING)
logging.getLogger("Lark").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("uvicorn.error").setLevel(logging.INFO)
logging.getLogger("websockets").setLevel(logging.WARNING)

# Silence noisy subsystem loggers
logging.getLogger("gateway.connection_manager").setLevel(logging.WARNING)
logging.getLogger("gateway.routes.websockets").setLevel(logging.WARNING)
logging.getLogger("sessions.store").setLevel(logging.WARNING)
logging.getLogger("sentence_transformers").setLevel(logging.WARNING)
logging.getLogger("transformers").setLevel(logging.WARNING)
logging.getLogger("torch").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("pkg_resources").setLevel(logging.ERROR)


def _check_macos_permissions():
    """Check macOS Accessibility & Screen Recording permissions. Warn if missing."""
    import platform

    if platform.system() != "Darwin":
        return

    issues = []

    # Check Accessibility permission (required for pyautogui click/type)
    try:
        import subprocess

        result = subprocess.run(
            ["osascript", "-e", 'tell application "System Events" to tell process "Finder" to return name'],
            capture_output=True,
            timeout=3,
        )
        if result.returncode != 0:
            issues.append("Accessibility")
    except Exception:
        pass

    # Check Screen Recording permission (required for screenshots on macOS 10.15+)
    try:
        from PIL import ImageGrab

        img = ImageGrab.grab(bbox=(0, 0, 1, 1))
        if img is None or img.size == (0, 0):
            issues.append("Screen Recording")
    except Exception:
        issues.append("Screen Recording")

    if issues:
        print()
        print("=" * 60)
        print("  macOS Permissions Required")
        print("=" * 60)
        for perm in issues:
            print(f"  - {perm}: NOT granted")
        print()
        print("  Fix: System Settings → Privacy & Security →")
        for perm in issues:
            if perm == "Accessibility":
                print(f"    1. {perm} → Add your Terminal app and enable it")
            else:
                print(f"    2. {perm} → Add your Terminal app and enable it")
        print()
        print("  Opening System Settings...")
        print("=" * 60)
        print()
        try:
            subprocess.run(
                ["open", "x-apple.systempreferences:com.apple.preference.security?Privacy"],
                capture_output=True,
                timeout=3,
            )
        except Exception:
            pass
    else:
        logger.info("macOS permissions OK (Accessibility + Screen Recording).")


def _preflight_check():
    """Startup preflight: validate environment and permissions."""
    from utils.config import settings as _s

    # macOS permission self-check
    import platform

    if platform.system() == "Darwin":
        _check_macos_permissions()

    errors = []
    warnings = []

    # Auto-generate GATEWAY_API_KEY if missing to ensure baseline security
    if not _s.GATEWAY_API_KEY:
        import secrets

        new_key = secrets.token_hex(16)
        env_path = os.path.join(project_root, ".env.local")
        with open(env_path, "a", encoding="utf-8") as f:
            f.write(f"\n# Auto-generated by Rooster for secure Dashboard access\nGATEWAY_API_KEY={new_key}\n")
        _s.GATEWAY_API_KEY = new_key
        os.environ["GATEWAY_API_KEY"] = new_key
        logger.warning(f"🔒 GATEWAY_API_KEY is not set. Auto-generated a secure random key: {new_key}")
        logger.warning("Please check your .env.local file. You will need this key to access the Dashboard.")

    # Check at least one provider has an API key
    providers = {
        "ZHIPU_KEY (智谱)": _s.ZHIPU_KEY,
        "MIMO_KEY (小米)": _s.MIMO_KEY,
        "JIUTIAN_KEY (九天)": _s.JIUTIAN_KEY,
        "CLOUD_KEY (云端)": _s.CLOUD_KEY,
    }
    has_any_key = any(v for v in providers.values())
    if not has_any_key:
        # Check if local model server is reachable
        local_ok = False
        try:
            import httpx

            with httpx.Client(timeout=2.0) as c:
                r = c.get(f"{_s.LOCAL_URL.rstrip('/')}/models")
                local_ok = r.status_code < 500
        except Exception:
            pass
        if local_ok:
            warnings.append("No cloud API keys configured. Using local model only (may be slow/limited).")
        else:
            errors.append(
                "No LLM API keys configured and local model server is unreachable.\n"
                "Please set at least one key in .env.local:\n"
                "  - ZHIPU_KEY=...  (智谱, recommended)\n"
                "  - MIMO_KEY=...   (小米)\n"
                "  - CLOUD_KEY=...  (OpenAI-compatible)\n"
                "Run: cp .env.local.example .env.local && edit .env.local"
            )

    if not _s.CLOUD_MODEL and not _s.ZHIPU_MODEL and not _s.MIMO_MODEL:
        warnings.append("No model name configured. Using provider defaults.")

    if errors:
        if sys.stdin.isatty():
            print()
            if _interactive_setup():
                return  # setup succeeded, continue to main()
        print("\n" + "=" * 60)
        print("  Rooster Preflight Check FAILED")
        print("=" * 60)
        for e in errors:
            print(f"  ERROR: {e}")
        print("=" * 60)
        print("  Fix the above issues and restart.")
        print("  Quick start: rooster init")
        print("=" * 60 + "\n")
        sys.exit(1)

    if warnings:
        for w in warnings:
            logger.warning(f"Preflight warning: {w}")

    logger.info("Preflight check passed.")


# ── Interactive setup wizard ────────────────────────────────────────────────

_PROVIDERS = [
    ("Zhipu AI", "ZHIPU_KEY", "glm-4-flash", "https://open.bigmodel.cn/api/paas/v4"),
    ("Xiaomi MiMo", "MIMO_KEY", "MiMo-7B", ""),
    ("OpenAI-compatible", "CLOUD_KEY", "gpt-4o", "https://api.openai.com/v1"),
    ("Jiutian", "JIUTIAN_KEY", "", ""),
    ("Local model server", "LOCAL_KEY", "local", "http://127.0.0.1:8080/v1"),
]


def _interactive_setup() -> bool:
    """Interactive setup wizard — prompts for API keys and writes .env.local.

    Returns True if at least one key was saved and preflight passes.
    """
    print("=" * 60)
    print("  Welcome to Rooster!")
    print("  No LLM API keys found. Let's set one up.")
    print("=" * 60)
    print()
    print("  Choose a provider (enter number):")
    for i, (name, key_name, default_model, _) in enumerate(_PROVIDERS, 1):
        print(f"    {i}. {name:25s}  ({key_name})")
    print()

    try:
        choice = input("  Provider [1]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return False

    if not choice:
        choice = "1"
    try:
        idx = int(choice) - 1
        if idx < 0 or idx >= len(_PROVIDERS):
            raise ValueError
    except ValueError:
        print("  Invalid choice.")
        return False

    name, key_name, default_model, default_url = _PROVIDERS[idx]

    if key_name == "LOCAL_KEY":
        # Local model — no key needed, just check URL
        url = input(f"  Model server URL [{default_url}]: ").strip() or default_url
        env_lines = [
            f"LOCAL_URL={url}",
            f"LOCAL_MODEL={default_model}",
        ]
    else:
        try:
            api_key = getpass.getpass(f"  Enter {name} API Key: ")
        except (EOFError, KeyboardInterrupt):
            print()
            return False
        if not api_key.strip():
            print("  No key entered.")
            return False

        model = input(f"  Model name [{default_model}]: ").strip() or default_model
        env_lines = [f"{key_name}={api_key.strip()}"]
        # Add model name and optional base URL
        model_key = key_name.replace("_KEY", "_MODEL")
        env_lines.append(f"{model_key}={model}")
        if default_url:
            base_url_key = key_name.replace("_KEY", "_BASE_URL")
            url = input(f"  Base URL [{default_url}]: ").strip() or default_url
            env_lines.append(f"{base_url_key}={url}")

    # Write to .env.local
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env.local")
    existing_lines = []
    if os.path.exists(env_path):
        with open(env_path, encoding="utf-8") as f:
            existing_lines = f.readlines()

    # Merge: update existing keys, append new ones
    existing_keys = set()
    for line in existing_lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            existing_keys.add(stripped.split("=", 1)[0].strip())

    with open(env_path, "a", encoding="utf-8") as f:
        if existing_lines and not existing_lines[-1].endswith("\n"):
            f.write("\n")
        for entry in env_lines:
            k = entry.split("=", 1)[0]
            if k not in existing_keys:
                f.write(entry + "\n")

    print(f"\n  Saved to .env.local ({len(env_lines)} entries)")
    print("  You can edit .env.local anytime to add more providers.\n")

    # Reload env and re-validate
    load_dotenv(dotenv_path=".env.local", override=True)
    return True


async def main():
    """
    Rooster top-level startup entry.
    Uses "dual-driver" mode:
    1. Background Gateway + persistent connection channel.
    2. Console interaction (CLI).
    """
    _preflight_check()

    # Suppress benign ConnectionResetError on Windows ProactorEventLoop pipe close
    if sys.platform == "win32":
        loop = asyncio.get_event_loop()
        _orig = loop.get_exception_handler() or loop.default_exception_handler

        def _quiet_handler(loop, context):
            exc = context.get("exception")
            if isinstance(exc, ConnectionResetError) and getattr(exc, "winerror", None) == 10054:
                return
            _orig(loop, context)

        loop.set_exception_handler(_quiet_handler)

    launcher = RoosterLauncher()

    try:
        # 并发执行网关与终端交互
        # Concurrently execute gateway and terminal interaction
        await asyncio.gather(launcher.launch_gateway(), launcher.launch_cli())
    except (KeyboardInterrupt, SystemExit):
        logger.info("捕获到退出信号。")  # Exit signal caught
    except Exception as e:
        logger.exception(f"Rooster 系统运行中发生致命崩溃: {e}")  # Fatal crash in Rooster system
        # [P1 不死守卫] 关键点：必须以非零码退出，否则守护进程无法感知异常。
        # [P1 Immortal Guard] Critical: must exit with non-zero code, otherwise the daemon cannot detect the anomaly
        sys.exit(1)
    finally:
        # 兜底清理资源
        # Fallback resource cleanup
        await launcher.cleanup()


def main_cli():
    """pip install 后的 CLI 入口点 (pyproject.toml [project.scripts])"""  # CLI entry point after pip install
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
        # 修复 Windows 控制台 GBK 编码导致 emoji 日志崩溃
        # Fix Windows console GBK encoding causing emoji log crashes
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")

    # Handle subcommands
    if len(sys.argv) > 1 and sys.argv[1] == "init":
        if _interactive_setup():
            print("  Setup complete! Run 'rooster' to start.")
        else:
            print("  Setup cancelled.")
        return

    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main_cli()
